version: 2
jobs:
  build:
    working_directory: /srv/unity/applywith-sdk
    docker:
      - image: node:8.0.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn
          command: if ! which yarn > /dev/null; then npm install yarn; fi
      - run:
          name: Image Deps
          command: apt-get update && apt-get install -y -qq ocaml libelf-dev
      - run:
          name: Install Deps
          command: yarn
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: yarn build
      - run:
          name: Test
          command: yarn test -- --maxWorkers 2
      - run:
          name: Validating
          command: yarn lint
