version: 2
jobs:
  build:
    working_directory: ~/applywith-sdk
    docker:
      - image: node:8.0.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Image Deps
          command: apt-get update && apt-get install -y -qq ocaml libelf-dev
      - run:
          name: Install Deps
          command: npm install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
      - run:
          name: Validating
          command: npm run lint
